FROM node:slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm install typescript

# Copy all files from the current directory to the working directory in the container
COPY . .

RUN npx tsc -b

EXPOSE 8080

# Set environment variable for production
ENV NODE_ENV=production

# Start the Next.js app
CMD ["npm", "start"]
